server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myGez?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp  application:    name: gez-wechatApplet #eureka注册实例显示这个名称
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug
#------------------------------------------------EUREKA---------------------------------------------
 
#eureka注册地址
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
      #通过ip注册
  instance:    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    hostname: 127.0.0.1